### ISSUE TITLE
Record view not usable on firefox

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [NeoCoderMatrix86/AudioCuesheetEditor#138]
**Describe the bug**
On firefox after loading record view, the exception comes up:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: error loading dynamically imported module
      
Microsoft.JSInterop.JSException: error loading dynamically imported module

   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at FFmpegBlazor.FFmpegFactory.Init(IJSRuntime runtime, String cdnURL)
   at AudioCuesheetEditor.Pages.ViewModeRecord.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

Info from console:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://unpkg.com/@ffmpeg/ffmpeg@0.9.7/dist/ffmpeg.min.js. (Grund: CORS-Anfrage schlug fehl).

Modul-Quell-URI ist in diesem Dokument nicht erlaubt: "https://unpkg.com/@ffmpeg/ffmpeg@0.9.7/dist/ffmpeg.min.js".

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by NeoCoderMatrix86** [comment]
https://github.com/sps014/FFmpegBlazor/issues/6

**Comment by NeoCoderMatrix86** [comment]
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/166

**Comment by NeoCoderMatrix86** [comment]
https://github.com/NeoCoderMatrix86/AudioCuesheetEditor/issues/154 handles the long term strategy.
