### ISSUE TITLE
Out of memory exception when using large mp3 files

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [NeoCoderMatrix86/AudioCuesheetEditor#323]
I get an out of memory exception when using large mp3 files for splitting via split points:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_OutOfMemoryException
System.OutOfMemoryException: Arg_OutOfMemoryException
   at AudioCuesheetEditor.Model.IO.Audio.AudioConverterService.SplitAudiofileAsync(Audiofile audiofile, TimeSpan from, Nullable`1 to)
   at AudioCuesheetEditor.Model.IO.Export.ExportfileGenerator.GetAudiofileContentAsync(String audiofileName, Nullable`1 from, SplitPoint splitPoint)
   at AudioCuesheetEditor.Model.IO.Export.ExportfileGenerator.GenerateExportfilesAsync(ExportType exportType)
   at AudioCuesheetEditor.Shared.ModalExportdialog.GenerateExportfiles_Clicked()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.Button.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
u @ blazor.webassembly.js:1

**Comment by NeoCoderMatrix86** [comment]
Using a 405 mb file allocates about 2,5 GB of memory from the browser tab.

**Comment by NeoCoderMatrix86** [comment]
Remove FFMpeg and enable the user to set audio file name for each split point.
